
echo # installing python ...
choco install python -y 
echo # refreshing environment vars ...
RefreshEnv
echo # installing azure-batch sdk for python ...
pip install azure-batch
echo Exit Code is %errorlevel%
exit /b %errorlevel%
